.rubocop.yml:
  default_configs:
    Style/SignalException:
      Enabled: false
    Layout/HeredocIndentation:
      Enabled: false
Gemfile:
  optional:
    ":development":
      - gem: beaker
        version: '~> 5.0'
        from_env: BEAKER_VERSION
      - gem: beaker-abs
        from_env: BEAKER_ABS_VERSION
        version: '~> 1.0'
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION
      - gem: beaker-puppet
        from_env: BEAKER_PUPPET_VERSION
        version: '~> 3.0'
      # We can unpin async when we move to Ruby 3
      - gem: async
        version: '~> 1'
      - gem: beaker-module_install_helper
      - gem: beaker-puppet_install_helper
      - gem: nokogiri
    ":system_tests":
      - gem: voxpupuli-acceptance

appveyor.yml:
  delete: true
.travis.yml:
  delete: true
.github/workflows/release.yml:
  unmanaged: false
.github/workflows/release_prep.yml:
  unmanaged: false
.gitlab-ci.yml:
  delete: true
# We still use the Vox acceptance Rake task instead of Litmus
Rakefile:
  requires:
    - voxpupuli/acceptance/rake
